# CirclePractice Configuration

# Default spawn location
spawn:
  world: world
  x: 0.5
  y: 100.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

# Plugin settings
settings:
  # Time (in seconds) players wait in the queue before starting a duel
  queue-time: 60

  # Maximum duel duration (in seconds)
  duel-time: 900

  # Whether spectators are allowed
  spectator-enabled: false

# Coin rewards for different activities
rewards:
  # Coins earned per kill in FFA
  kill: 10
  
  # Coins earned for winning a duel
  duel-win: 25
  
  # Bonus coins for killstreaks (every 5 kills)
  killstreak-bonus: 50
  
  # Kit multipliers for duel wins
  kit-multipliers:
    NoDebuff: 1
    FFA: 1
